replicaCount: 1
env: {}
image:
  repository: "mariadb"
  pullPolicy: IfNotPresent
  tag: "latest"

MYSQL_DATABASE: db-mediawiki
MYSQL_USER: user-sql

request_storage_pvc: "5Gi"
storage: 
  sku: StandardSSD_LRS

service:
  type: ClusterIP
  port: 3306
  targetport: 3306

serviceAccount:
  create: false
  annotations: {}
  name: ""

resources: {}