apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.env }}-pvc
  labels:
    {{- include "mediawiki.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.name }}-{{ .Values.env }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.request_storage_pvc }}
