### Build & Release
name: $(Build.BuildId)

trigger:
- main

pr:
- '*'

parameters:
- name: Environment
  type: string
  default: D
  values:
  - D
  - T
  - O
  - I

- name: Region
  type: string
  default: weu
  values:
  - bzn
  - cnc 
  - cin

- name: Subscription
  type: string
  default: 'Azure RM - Assignment'
  values:
  - Azure Assignment - works

- name: configureCluster
  displayName: 'Configure Cluster?'
  type: boolean
  default: true

- name: regionObject
  displayName: 'Region Map'
  type: object
  default:
  - bzn: 'brazilsouth'
  - cnc: 'canadacentral'
  - cin: 'centralindia'

variables:
## Variable group from pipelines library
- group: Assignment-values
### Nigthly vars
- name: environment
  ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    value: 'T'
  ${{ else }}:
    value: '${{ parameters.Environment }}' 
- name: region
  ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    value: 'weu'
  ${{ else }}:
    value: '${{ parameters.Region }}'
- name: subscription
  ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    value: 'Azure RM - QA (Ops)'
  ${{ else }}:
    value: '${{ parameters.Subscription }}'    
### Template vars    
- template: templates/vars/cd-release-vars.yml
  parameters: 
    environment: ${{ variables.environment }}
    region: ${{ variables.region }}
### Job name vars

stages:
- stage: Docker_build_push_ACR
  jobs:
  - job: Build_and_Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        command: login
        containerRegistry: App-ACR
    - task: Docker@2
      displayName: Build and push Image for mediawiki App
      inputs:
        command: buildAndPush
        repository: ${{ variables.environment }}-mediawiki
        dockerfile: 'Apps_conf/Dockerfile'
        containerRegistry: App-ACR
        tags: |
          latest

    - task: Docker@2
      displayName: Build and push Image for mariadb
      inputs:
        command: buildAndPush
        repository: ${{ variables.environment }}-mariadb
        dockerfile: 'Apps_conf/Dockerfile.mariadb'
        containerRegistry: App-ACR
        tags: |
          latest

- stage: Configure
  dependsOn: Docker_build_push_ACR
  displayName: 'Configure Cluster Stage ${{ variables.environment }}' 
  pool:
    vmImage: ubuntu-latest  
  jobs:              
  - displayName: 'Configure Cluster ${{ variables.environment }} ${{ variables.region }}'
    condition: eq('${{ variables.configureCluster }}', 'true')
    environment: '${{ variables.environment }}'
    timeoutInMinutes: 30
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/steps/pre-cluster-config-steps.yml
            parameters:    
              environment: ${{ variables.environment }}
              region: ${{ variables.region }}
              subscription: ${{ variables.subscription }}