replicaCount: 1
env: dev
image:
  repository: D-mariadb
  pullPolicy: IfNotPresent
  tag: "latest"

MYSQL_DATABASE: db-mediawiki
MYSQL_USER: user-sql

request_storage_pvc: "5Gi"
storage: 
  sku: StandardSSD_LRS
  size: "10Gi"

service:
  type: ClusterIP
  port: 3306
  targetport: 3306

serviceAccount:
  create: false
  annotations: {}
  name: ""

resources: {}
