replicaCount: 1

image:
  repository: mariadb
  pullPolicy: IfNotPresent
  tag: "latest"

MYSQL_DATABASE: db-mediawiki
MYSQL_USER: user-sql

service:
  type: ClusterIP
  port: 3306
  targetport: 3306

serviceAccount:
  create: false
  annotations: {}
  name: ""

resources: {}
