replicaCount: 2
env: dev
image:
  repository: D-mediawiki
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 8080
  targetport: 8080

request_storage_pvc: "100Mi"

storage: 
  name: mediawiki-storage
  sku: StandardSSD_LRS

ingress:
  enabled: true
  annotations: "kubernetes.io/ingress.class: azure/application-gateway"
  hosts:
    - host: test.com
      paths: []
  tls: []

resources: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 60
