apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.env }}-pvc
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  storageClassName: mariadb-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.request_storage_pvc }}