{{- if .Values.freshclamConfig -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: clamav-freshclam
  labels:
    app: clamav
    chart: {{ template "clamav.chart" . }}
    release: clamav
    heritage: {{ .Release.Service }}
data:
  freshclam.conf:
    {{ toYaml .Values.freshclamConfig | indent 4 }}
{{- end }}