apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: clamav
    helm.sh/chart: {{ include "clamav.chart" . }}
    app.kubernetes.io/instance: clamav
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: clamavport
  selector:
    app.kubernetes.io/name: clamav
    app.kubernetes.io/instance: clamav