apiVersion: {{ default "apps/v1beta2" .Values.kubeMeta.deploymentApiVersion }}
kind: StatefulSet
metadata:
  name: clamav
  labels:
    app.kubernetes.io/name: clamav
    helm.sh/chart: {{ include "clamav.chart" . }}
    app.kubernetes.io/instance: clamav
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: clamav
      app.kubernetes.io/instance: clamav
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clamav
        app.kubernetes.io/instance: clamav
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      # init the virus signatures before ronning the clamd daemon
      initContainers:
        - name: clamav-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', '-c', "stat /data/main.cvd || freshclam"]
          volumeMounts:
          - name: data-volume
            mountPath: /data
            subPath: clamav
{{- if .Values.freshclamConfig }}
          - name: freshclam-config-volume
            mountPath: /etc/clamav/freshclam.conf
            subPath: freshclam.conf
{{- end }}
{{- if .Values.clamdConfig }}
          - name: clamd-config-volume
            mountPath: /etc/clamav/clamd.conf
            subPath: clamd.conf
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
      containers:
        - name: clamav
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: data-volume
            mountPath: /data
            subPath: clamav
{{- if .Values.freshclamConfig }}
          - name: freshclam-config-volume
            mountPath: /etc/clamav/freshclam.conf
            subPath: freshclam.conf
{{- end }}
{{- if .Values.clamdConfig }}
          - name: clamd-config-volume
            mountPath: /etc/clamav/clamd.conf
            subPath: clamd.conf
{{- end }}
          ports:
            - name: clamavport
              containerPort: 3310
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: clamavport
            initialDelaySeconds: 600
          readinessProbe:
            tcpSocket:
              port: clamavport
            initialDelaySeconds: 180
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
{{- if .Values.freshclamConfig }}
        - name: freshclam-config-volume
          configMap:
            name: clamav-freshclam
{{- end }}
{{- if .Values.clamdConfig }}
        - name: clamd-config-volume
          configMap:
            name: clamav-clamd
{{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.dockerConfigJson }}
      imagePullSecrets:
      - name: clamav-reg-cred
{{- end }}